### ISSUE TITLE
Pixelmon cant use the pc

### ISSUE THREAD

**Issue by NoirBat** [AOF-Dev/MCinaBox#256]
So i installed forge 1.12.2 2847 and the pixelmon mod but every time i open the pc the game freezes and crashes.
Im not sure if this is the place to put it. Maybe its just a pixelmon bug.

**Comment by NoirBat** [comment]
Here is the crash report.
[crash-2020-07-14_05.11.12-client.txt](https://github.com/longjunyu2/MCinaBox/files/4921934/crash-2020-07-14_05.11.12-client.txt)

**Comment by bghyt** [comment]
so pixelmon does somthing to the mouse but the issue is there is no "physical mouse" so to speak, just some software pretending / tricking minecraft there is a mouse so you can in some way click and play the game, due to this i believe it makes it incompatible with pixelmon mod currently, There is no fix to this as far as i'm aware.
