### ISSUE TITLE
F-Droid availability?

### ISSUE THREAD

**Issue by CrimsonFork** [AOF-Dev/MCinaBox#264]
Any chance to see this app on [F-Droid](https://f-droid.org)? It's a Google Play "replacement" for F(L)OSS apps only.

**Comment by bghyt** [comment]
The app currently is in alpha / beta state, no where near finish and this app also lets you pirate and play minecraft java without paying so that in the least will stop it from going onto any sort of legal store.

**Comment by MrHeating** [comment]
I get where you're comimg from, but I eould hardly describe F-Droid as a "legal store", since it can't be used for anything commercial, and there also are no requirements to any state of polish, as long as there is some functionality.

The only real requirements are open source and no proprietary dependencies (such as Google analytics).

And before you ask, no, Minecraft is not a dependency, more like a non-free extension that isn't included with thebase app.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bghyt** [comment]
> I get where you're comimg from, but I eould hardly describe F-Droid as a "legal store", since it can't be used for anything commercial, and there also are no requirements to any state of polish, as long as there is some functionality. The only real requirements are open source and no proprietary dependencies (such as Google analytics). And before you ask, no, Minecraft is not a dependency, more like a non-free extension that isn't included with thebase app. -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

Because you can download minecraft without paying for it this app promotes piracy and breaks the law, F-Droid will not allow it on the store, F-Droid is a legal store.

**Comment by Soharuda** [comment]
@bghyt The app does not promote but does allow. Theres a difference on how that works while still riding the same sensitivity as legal limits.

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
