### ISSUE TITLE
1.13.1+ graphics issue

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#278]
I might have known the problem. The problem is in the LWJGL v 3.2.3 . I think there are some bugs in it which is causing this graphics issue in Minecraft Java 1.13.1+. So, LWJGL v 3.2.2 or 3.2.1 can solve this problem. Idk, maybe, because when I checked the .minecraft/libraries/org/lwjgl folder, there are LWJGL3 files with the version of both 3.2.2 and 3.2.1, but not the 3.2.3. But the other problem is, there are no arm/arm64 binary of these. Idk, maybe it's true. If it's not, then I might be wrong because I am not a programmer.

**Comment by Soharuda** [comment]
Thankfully java JAR and CLASS files are not binary. Sure, the .class files are compiled, but not to a specific instruction set for CPUs. The class files are just the source code converted so that the JVM can understand and run it. The JVM itself does all of the heavy lifting :)

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
