### ISSUE TITLE
(Việt Nam) ứng dụng cần được nâng cấp, memory cho phép cao hơn,tích hợp nhiều tính năng PC hơn. 

### ISSUE THREAD

**Issue by lephuc0167283** [AOF-Dev/MCinaBox#297]
thank

**Comment by lephuc0167283** [comment]
Memory higher, integrate more mod then the app will develop extremely strong.

**Comment by TSaltedfishKing** [comment]
看不懂

**Comment by SkilledHasBadPC** [comment]
Updates? Yes sure it will come out
Higher memory limit? nah bro ask Android because it's the one limiting the ram
PC mechanics? Not sure what do you want from that
I mean we have keyboard, game controlling keyboard, mouse buttons, joystick, and many other things
What would you even need more than that
