### ISSUE TITLE
How to allocate more than 1gb of ram? 

### ISSUE THREAD

**Issue by leetmussc** [AOF-Dev/MCinaBox#433]
I need help with allocating more than 1gb of ram for aarch64 v0. 1.4-p3

**Comment by Kotarou2k4** [comment]
Do it crash when you setting more ram ?

**Comment by leetmussc** [comment]
I can set any ram and it doesn't crash

**Comment by leetmussc** [comment]
But minecraft only allows 1gb to be used.

**Comment by hamid12121** [comment]
Same for me but I can up that mor 1G because app close

**Comment by hamid12121** [comment]
May be we use java Aarch64 get upper memory?

**Comment by longjunyu2** [comment]
If your device's cpu abi is armeabi-v7a, then you can only use aarch32 truntime. In this case, it is nearly impossible to allocate more memory then 1024mb (because of the limitation of Heapsize in build.prop).
If your devices's cpu abi is arm64-v8a, then you can only use aarch64 runtime. In this.case, it is possible to allocate more memory. But do not allocate memory more than your physics memory.

**Comment by jamo-lcr** [comment]
I have got a Snapdragon 845 (64 Bit )and IT Crashes by 1024 MB RAM why and how could i fix this?
(-:

**Comment by jamo-lcr** [comment]
And My Kernel Architektur ist x64

**Comment by artdeell** [comment]
Maybe you should clean up background apps?

пн, 5 окт. 2020 г., 00:40 jamo-lcr <notifications@github.com>:
