### ISSUE TITLE
Support 1.16.x PLS!

### ISSUE THREAD

**Issue by ABCCCC55645687** [AOF-Dev/MCinaBox#467]
Crash with 1.16.x on AArch64 RuntimePack.....
Please update boat to boat4!And make RuntimePack support boat4 or 1.16.1！Thanks!!!

**Comment by KeyzGames** [comment]
nah, this is why i always play on the servers than my own world. It feels weird when some features are not added.

**Comment by longjunyu2** [comment]
MCinaBox have already updated to boat4.(Version 0.1.4 preview.)
AArch64 crash 1.13+, this is because libglfw.so can not be dlopen normally.
It seems that the target api level is higher than 21 when building libglfw.so.
I will fix this by updating a new runtime.
But I need some time...I still in university, and I have many other things to do..
