### ISSUE TITLE
Auto Build

### ISSUE THREAD

**Issue by AyHa1810** [AOF-Dev/MCinaBox#484]
How about setting up an Auto builder? This way, people can test the latest compiled version with latest commits. 
I found this two tutorials about it.
[Tutorial 1](https://docs.docker.com/docker-hub/builds/) 
[Tutorial 2](https://medium.com/@_oleksii_/set-up-automated-builds-using-github-and-docker-hub-12c3e0f18eba) 
Idk which one you should choose.

**Comment by AyHa1810** [comment]
@longjunyu2 what do you think about it?

**Comment by longjunyu2** [comment]
@AyHa1810 Hi AyHa1810.
Sorry that I reply to you so late.
I have to spend a little bit of time dealing with emails and questions on GitHub, because I have a lot of classes every day,
I'm glod to build the latest version of mcinbox automatically.
The idea of building the lastest version of mcinabox is good. This will let users get lastest version in time and report the bugs.

But I want mcinabox to adopt a lazy version update strategy, because it helps to focus on the problems of one version rather than those of some versions.
 I can't guarantee that a bug will be fixed in a certain version. This will mislead users to iterate over and over again, but the experience is not very good. This was my thought in the past.

But I will still try your suggestion.
Tutorial 1 looks good.
Thanks a lot.

**Comment by yonderbread** [comment]
We should call it the nightly/experimental build.

**Comment by AyHa1810** [comment]
@longjunyu2 that's fine. I don't really mind if you reply me late. :)

**Comment by Kotarou2k4** [comment]
Hey @longjunyu2, you can realize that mostly every don't know how to report bugs so can you make like on pictures below, and this will working like a guide how they can report bug (but I don't know how this working or make this):
![IMG_20201008_183329](https://user-images.githubusercontent.com/65490046/95453528-36da8600-0995-11eb-9c8d-46adc6321366.jpg)
![IMG_20201008_183343](https://user-images.githubusercontent.com/65490046/95453535-39d57680-0995-11eb-8524-806c2c90db50.jpg)
This is Osu!lazer project on github

**Comment by AyHa1810** [comment]
@longjunyu2 well, I managed to find [this](https://medium.com/@AndreSand/building-android-with-docker-8dbf717f54d4) tutorial about android app built, but I don't know about the auto-build part. I think you had to modify the `Docker` file to make it auto-build.

**Comment by AyHa1810** [comment]
Yeah! The auto-build is finally here! Thanks to @LegacyGamerHD in #572 for implementing this!
