### ISSUE TITLE
Keyboard mouse support doesn't work and when i use my touch screen doesn"t work

### ISSUE THREAD

**Issue by chinh4thepro** [AOF-Dev/MCinaBox#688]
I try to type stuff but nothing happens and the tab and the enter/return key only works. I try using my mouse but when I try to click it doesn't work and the mouse pointer is off, and when I try to use my screen it doesn't work.

**Comment by PeterScorPioN** [comment]
This keyboard has two modes, with typing enabled na typing disabled(you can toggle this mode in the top right corner of the keyboard, where it says "Enable Typing"). So when typing is disabled, the keyboard's buttons work as in-game controls, which means that you can only play with these buttons. You have to enable that option called "Enable typing" (top right corner, as i mentioned upper...) in order to type anything. That's it. I think i was helpful.😁
