### ISSUE TITLE
big screen phones

### ISSUE THREAD

**Issue by PHLA7** [AOF-Dev/MCinaBox#784]
The app is not completely compatible with big screen phones (in my case the motorola one fusion that has a 9:20 ratio) 
![Screenshot_20210102-195434](https://user-images.githubusercontent.com/62392976/103468097-63076800-4d34-11eb-9541-0a09f8e6d097.png)
![Screenshot_20210102-194454](https://user-images.githubusercontent.com/62392976/103468099-64d12b80-4d34-11eb-9285-58b143f31ac6.png)

**Comment by FreddyFeuerstein** [comment]
you need to enable fullscreen in appinfo (settings -> apps -> MCinaBox) manually, because android 9 or above disables it automatically due to compatiblity reasons with android 4 apps. I did that on my galaxy a 40 and it solved the problem in 80% of the apps i use. 2 apps didnt work with it but because it can be set for every app seperately, it wasnt a big problem. i just turned it off for those apps and left it on for the other apps.

Screenshot showing MCinaBox in fullscreen mode:
![Screenshot](https://user-images.githubusercontent.com/55027065/103478956-7238f500-4dca-11eb-9c6d-3c5eacc7f505.jpg)
